table Medidas
	lineageTag: 507e824b-2b5d-416d-bb7f-70f1ce896f3a

	measure 'Total a Receber' = SUM(f_Receber[Valor Total])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.2 Entradas
		lineageTag: 5a1c43f6-6f64-41b3-9cd9-f12a82f6ec08

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Total a receber em Aberto' = SUM(f_Receber[Valor em Aberto])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.2 Entradas
		lineageTag: 159d1f35-e27c-4d24-add1-ad08d4915fdd

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Total Recebido' = SUM(f_Recebimentos[Valor Total])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.2 Entradas
		lineageTag: dc01cd2a-3cdb-40a3-8f34-aef61864aada

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Total a receber Atrasados' =
			
			CALCULATE(
			    [Total a Receber],
			    f_Receber[Data Agendada] < TODAY()
			)
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.2 Entradas
		lineageTag: 81f7df3e-8077-4d0e-ac27-0cc1e0bffaea

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Total a Pagar' = SUM(f_Pagar[Valor Total])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.3 Saídas
		lineageTag: 730f1336-f174-4367-ac20-7f1324ce6fa1

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Total a pagar em Aberto' = SUM(f_pagar[Valor em Aberto])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.3 Saídas
		lineageTag: d7582990-6faf-4c62-a679-5e17f90c357e

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Total Pago' = SUM(f_Pagamentos[Valor Total])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.3 Saídas
		lineageTag: 36a68a01-e220-4bfb-9ae7-f0c7ed5c5e81

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Total a pagar Atrasados' =
			
			CALCULATE(
			    [Total a pagar],
			    f_pagar[Data Agendada] < TODAY()
			)
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.3 Saídas
		lineageTag: 8548b835-6f3c-4aa0-acfc-9a67cd00699e

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure ValorBalancete =
			
			SUM(f_Balancete_Geral[Valor Total])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.1 Disponibilidade Imediata
		lineageTag: cab5cadd-789f-410f-a2cf-90001ba10bbf

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Saldo Inicial' =
			
			CALCULATE(
			    SUM(f_Recebimentos[Valor Total]),
			    f_Recebimentos[Categoria] = "Saldo Inicial"
			)
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.1 Disponibilidade Imediata
		lineageTag: c49589ff-39ac-487f-a77c-ac6403ad6382

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Saldo Atual' =
			
			[Total Recebido] - [Total Pago]
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.1 Disponibilidade Imediata
		lineageTag: 86650b16-49e1-456d-ae6e-e1eb2f96c2a9

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Saldo Previsto' =
			
			[Total a Receber] - [Total a Pagar] + [Saldo Atual]
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.1 Disponibilidade Imediata
		lineageTag: f510d850-2a16-492f-9cf1-88f2a8a6343c

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Entradas =
			
			CALCULATE(
			    SUM(f_Agregados_Gerais[Valor]),
			    f_Agregados_Gerais[Tipo] = "Entradas"
			)
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.1 Disponibilidade Imediata
		lineageTag: 3faef1cc-2670-4b0c-b0d4-eda7d21e7d56

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Saídas =
			
			CALCULATE(
			    SUM(f_Agregados_Gerais[Valor]),
			    f_Agregados_Gerais[Tipo] = "Saídas"
			)
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.1 Disponibilidade Imediata
		lineageTag: c86d006a-e4c4-4930-9a8d-c72630a6a42d

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Movimentação Líquida' = ```
			SUM(f_Balancete_Geral[cc_ValorFormatado]) 
			```
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.1 Disponibilidade Imediata
		lineageTag: 4a38d5aa-0ba1-4c2c-8eed-8d65547feeb6

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Saldo Acumulado líquido' =
			
			CALCULATE(
			    [Movimentação Líquida],
			    FILTER(ALL(d_Calendario[Data]), d_Calendario[Data] <= d_Calendario[Data])
			)
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.1 Disponibilidade Imediata
		lineageTag: da7ab416-00fb-4c5d-9da4-f5e4b0f545f5

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Saldo Final disponível' = [Saldo Acumulado líquido] + [Saldo Inicial]
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.1 Disponibilidade Imediata
		lineageTag: a73f7554-a224-4a41-959e-a271e16e2921

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Movimentacao Liquida SOB RISCO' = ```
			
			VAR DiasAtraso = [Atraso de Receita dias]
			VAR EntradasAtrasadas = 
			    CALCULATE(
			        [Total a Receber],
			        DATEADD( d_Calendario[Data], DiasAtraso, DAY )
			    )
			
			VAR SaidasSemAtraso = [Total a Pagar]
			
			RETURN
			    EntradasAtrasadas - SaidasSemAtraso
			```
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.4 Gestão de Riscos\1.4.1 Atraso de receita
		lineageTag: 22823c70-920a-4570-8a37-d5a92eb71ddb

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Movimentação - Data Quebra' = ```
			
			VAR _SaldoRisco = [Movimentacao Liquida SOB RISCO] // Medida que você já criou.
			
			RETURN
			    // Retorna a menor data (a primeira) que atende ao critério de risco.
			    MINX( 
			        // 1. Itera sobre todas as datas no contexto
			        FILTER( 
			            ALL(d_Calendario[Data]), 
			            // 2. Filtra apenas as datas onde o Saldo Sob Risco é negativo
			            [Movimentacao Liquida SOB RISCO] < 0 
			        ), 
			        // 3. Retorna a data (o contexto da linha atual)
			        d_Calendario[Data] 
			    )
			```
		formatString: General Date
		displayFolder: 1. INDICADORES\1.4 Gestão de Riscos\1.4.1 Atraso de receita
		lineageTag: 54b84a05-b653-4909-93c1-26d22a37610f

	measure 'Movimentação - Status' = ```
			
			VAR DataQuebra = [Movimentação - Data Quebra] // Sua medida que retorna a data de crise
			VAR DataHoje = TODAY()
			VAR DiasParaQuebra = DATEDIFF(DataHoje, DataQuebra, DAY) // Calcula a diferença em dias
			
			RETURN
			    IF(
			        ISBLANK(DataQuebra),
			        "CAIXA SAUDÁVEL (Risco Controlado)", // Se não houver data, está seguro.
			        
			        // Se houver data:
			        "PREJUÍZO em " & 
			        FORMAT(DiasParaQuebra, "#") & 
			        " dias (Risco Alto)"
			    )
			```
		displayFolder: 1. INDICADORES\1.4 Gestão de Riscos\1.4.1 Atraso de receita
		lineageTag: 8c35f692-efe9-4079-b5f7-3d76249d14cb

	measure 'Entradas Previstas (Risco de Inadimplência)' = [Total a Receber] * (1- 'aux_Risco Inadimplência'[Risco Inadimplência %])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.4 Gestão de Riscos\1.4.2 Inadimplência
		lineageTag: eefe7ab2-991f-4000-a6b6-8680d9356d14

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Saídas Previstas (Risco de Inadimplência)' = [Total a Pagar] * (1+ 'aux_Aumento despesas'[Valor aux_Aumento despesas])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.4 Gestão de Riscos\1.4.3 Aumento de despesas
		lineageTag: 4569e737-2033-45e6-9e1f-6501f2530568

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Movimentacao Liquida (RISCO TOTAL)' = ```
			
			VAR DiasAtraso = [Atraso de Receita dias]
			VAR PctInadimplencia = [Risco Inadimplência %]
			VAR PctAumentoCusto = [Valor aux_Aumento despesas]
			
			// 1. Aplica o Fator de Inadimplência e o Atraso (DATEADD)
			VAR EntradasAjustadas = 
			    CALCULATE(
			        [Total a Receber] * (1 - PctInadimplencia), // Aplica Inadimplência
			        DATEADD( d_Calendario[Data], DiasAtraso, DAY )    // Aplica Atraso
			    )
			
			// 2. Aplica o Fator de Aumento de Custo
			VAR SaidasAjustadas = 
			    [Total a Pagar] * (1 + PctAumentoCusto)
			
			RETURN
			    EntradasAjustadas - SaidasAjustadas
			```
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.4 Gestão de Riscos\1.4.4 Movimentação sob Riscos
		lineageTag: bbb39443-9a04-48f9-a923-018966459535

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Inadimplência - Data Quebra' = ```
			
			VAR _SaldoRisco = [Entradas Previstas (Risco de Inadimplência)] // Medida que você já criou.
			
			RETURN
			    // Retorna a menor data (a primeira) que atende ao critério de risco.
			    MINX( 
			        // 1. Itera sobre todas as datas no contexto
			        FILTER( 
			            ALL(d_Calendario[Data]), 
			            // 2. Filtra apenas as datas onde o Saldo Sob Risco é negativo
			            [Entradas Previstas (Risco de Inadimplência)] < 0 
			        ), 
			        // 3. Retorna a data (o contexto da linha atual)
			        d_Calendario[Data] 
			    )
			```
		formatString: General Date
		displayFolder: 1. INDICADORES\1.4 Gestão de Riscos\1.4.2 Inadimplência
		lineageTag: a795126e-5f59-43e5-a8d4-edf6dd59800e

	measure 'Inadimplência - Status' = ```
			
			VAR DataQuebra = [Inadimplência - Data Quebra] // Sua medida que retorna a data de crise
			VAR DataHoje = TODAY()
			VAR DiasParaQuebra = DATEDIFF(DataHoje, DataQuebra, DAY) // Calcula a diferença em dias
			
			RETURN
			    IF(
			        ISBLANK(DataQuebra),
			        "CAIXA SAUDÁVEL (Risco Controlado)", // Se não houver data, está seguro.
			        
			        // Se houver data:
			        "PREJUÍZO em " & 
			        FORMAT(DiasParaQuebra, "#") & 
			        " dias (Risco Alto)"
			    )
			```
		displayFolder: 1. INDICADORES\1.4 Gestão de Riscos\1.4.2 Inadimplência
		lineageTag: 86d917d5-0234-491f-9950-78eb9ea6b679

	measure 'Aumento Despesas - Data Quebra' = ```
			
			VAR _SaldoRisco = [Saídas Previstas (Risco de Inadimplência)] // Medida que você já criou.
			
			RETURN
			    // Retorna a menor data (a primeira) que atende ao critério de risco.
			    MINX( 
			        // 1. Itera sobre todas as datas no contexto
			        FILTER( 
			            ALL(d_Calendario[Data]), 
			            // 2. Filtra apenas as datas onde o Saldo Sob Risco é negativo
			            [Saídas Previstas (Risco de Inadimplência)] < 0 
			        ), 
			        // 3. Retorna a data (o contexto da linha atual)
			        d_Calendario[Data] 
			    )
			```
		formatString: General Date
		displayFolder: 1. INDICADORES\1.4 Gestão de Riscos\1.4.3 Aumento de despesas
		lineageTag: 3859224e-ce14-4de9-a67e-7371600209f6

	measure 'Aumento Despesas - Status' = ```
			
			VAR DataQuebra = [Aumento Despesas - Data Quebra] // Sua medida que retorna a data de crise
			VAR DataHoje = TODAY()
			VAR DiasParaQuebra = DATEDIFF(DataHoje, DataQuebra, DAY) // Calcula a diferença em dias
			
			RETURN
			    IF(
			        ISBLANK(DataQuebra),
			        "CAIXA SAUDÁVEL (Risco Controlado)", // Se não houver data, está seguro.
			        
			        // Se houver data:
			        "PREJUÍZO em " & 
			        FORMAT(DiasParaQuebra, "#") & 
			        " dias (Risco Alto)"
			    )
			```
		displayFolder: 1. INDICADORES\1.4 Gestão de Riscos\1.4.3 Aumento de despesas
		lineageTag: 8e328a8e-9bf4-4213-bd30-a9656c0d6bc7

	measure 'Movimentação Total - Data Quebra' = ```
			
			VAR _SaldoRisco = [Movimentacao Liquida (RISCO TOTAL)] // Medida que você já criou.
			
			RETURN
			    // Retorna a menor data (a primeira) que atende ao critério de risco.
			    MINX( 
			        // 1. Itera sobre todas as datas no contexto
			        FILTER( 
			            ALL(d_Calendario[Data]), 
			            // 2. Filtra apenas as datas onde o Saldo Sob Risco é negativo
			            [Movimentacao Liquida (RISCO TOTAL)] < 0 
			        ), 
			        // 3. Retorna a data (o contexto da linha atual)
			        d_Calendario[Data] 
			    )
			```
		formatString: General Date
		displayFolder: 1. INDICADORES\1.4 Gestão de Riscos\1.4.4 Movimentação sob Riscos
		lineageTag: 2dffcba9-7ead-411b-92e3-8b8968cae2a1

	measure 'Movimentação Total - Status' = ```
			
			VAR DataQuebra = [Movimentação - Data Quebra] // Sua medida que retorna a data de crise
			VAR DataHoje = TODAY()
			VAR DiasParaQuebra = DATEDIFF(DataHoje, DataQuebra, DAY) // Calcula a diferença em dias
			
			RETURN
			    IF(
			        ISBLANK(DataQuebra),
			        "CAIXA SAUDÁVEL (Risco Controlado)", // Se não houver data, está seguro.
			        
			        // Se houver data:
			        "PREJUÍZO em " & 
			        FORMAT(DiasParaQuebra, "#") & 
			        " dias (Risco Alto)"
			    )
			```
		displayFolder: 1. INDICADORES\1.4 Gestão de Riscos\1.4.4 Movimentação sob Riscos
		lineageTag: aeff9f51-f615-47df-9bfc-2d0e6ddad387

	column Medidas
		dataType: string
		isHidden
		lineageTag: 501e2c0d-bede-4853-99d0-c31ea8076abc
		summarizeBy: none
		sourceColumn: Medidas

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Medidas = m
		mode: import
		source =
				let
				    Fonte = ""
				in
				    Fonte

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Text

