table Medidas
	lineageTag: 507e824b-2b5d-416d-bb7f-70f1ce896f3a

	measure 'Total a Receber' = SUM(f_Receber[Valor Total])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.2 Entradas
		lineageTag: 5a1c43f6-6f64-41b3-9cd9-f12a82f6ec08

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Total a receber em Aberto' = SUM(f_Receber[Valor em Aberto])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.2 Entradas
		lineageTag: 159d1f35-e27c-4d24-add1-ad08d4915fdd

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Total Recebido' = SUM(f_Recebimentos[Valor Total])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.2 Entradas
		lineageTag: dc01cd2a-3cdb-40a3-8f34-aef61864aada

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Total a receber Atrasados' =
			
			CALCULATE(
			    [Total a Receber],
			    f_Receber[Data Agendada] < TODAY()
			)
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.2 Entradas
		lineageTag: 81f7df3e-8077-4d0e-ac27-0cc1e0bffaea

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Total a Pagar' = SUM(f_Pagar[Valor Total])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.3 Saídas
		lineageTag: 730f1336-f174-4367-ac20-7f1324ce6fa1

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Total a pagar em Aberto' = SUM(f_pagar[Valor em Aberto])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.3 Saídas
		lineageTag: d7582990-6faf-4c62-a679-5e17f90c357e

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Total Pago' = SUM(f_Pagamentos[Valor Total])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.3 Saídas
		lineageTag: 36a68a01-e220-4bfb-9ae7-f0c7ed5c5e81

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Total a pagar Atrasados' =
			
			CALCULATE(
			    [Total a pagar],
			    f_pagar[Data Agendada] < TODAY()
			)
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.3 Saídas
		lineageTag: 8548b835-6f3c-4aa0-acfc-9a67cd00699e

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure ValorBalancete =
			
			SUM(f_Balancete_Geral[Valor Total])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.1 Disponibilidade Imediata
		lineageTag: cab5cadd-789f-410f-a2cf-90001ba10bbf

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Saldo Inicial' =
			
			CALCULATE(
			    SUM(f_Recebimentos[Valor Total]),
			    f_Recebimentos[Categoria] = "Saldo Inicial"
			)
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.1 Disponibilidade Imediata
		lineageTag: c49589ff-39ac-487f-a77c-ac6403ad6382

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Saldo Atual' =
			
			[Total Recebido] - [Total Pago]
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.1 Disponibilidade Imediata
		lineageTag: 86650b16-49e1-456d-ae6e-e1eb2f96c2a9

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Saldo Previsto' =
			
			[Total a Receber] - [Total a Pagar] + [Saldo Atual]
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.1 Disponibilidade Imediata
		lineageTag: f510d850-2a16-492f-9cf1-88f2a8a6343c

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Entradas =
			
			CALCULATE(
			    SUM(f_Agregados_Gerais[Valor]),
			    f_Agregados_Gerais[Tipo] = "Entradas"
			)
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.1 Disponibilidade Imediata
		lineageTag: 3faef1cc-2670-4b0c-b0d4-eda7d21e7d56

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Saídas =
			
			CALCULATE(
			    SUM(f_Agregados_Gerais[Valor]),
			    f_Agregados_Gerais[Tipo] = "Saídas"
			)
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.1 Disponibilidade Imediata
		lineageTag: c86d006a-e4c4-4930-9a8d-c72630a6a42d

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Movimentação Líquida' = ```
			SUM(f_Balancete_Geral[cc_ValorFormatado]) 
			```
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.1 Disponibilidade Imediata
		lineageTag: 4a38d5aa-0ba1-4c2c-8eed-8d65547feeb6

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Saldo Acumulado líquido' =
			
			CALCULATE(
			    [Movimentação Líquida],
			    FILTER(ALL(d_Calendario[Data]), d_Calendario[Data] <= d_Calendario[Data])
			)
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.1 Disponibilidade Imediata
		lineageTag: da7ab416-00fb-4c5d-9da4-f5e4b0f545f5

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Saldo Final disponível' = [Saldo Acumulado líquido] + [Saldo Inicial]
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.1 Disponibilidade Imediata
		lineageTag: a73f7554-a224-4a41-959e-a271e16e2921

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Movimentacao Liquida SOB RISCO' = ```
			
			VAR DiasAtraso = [Atraso de Receita dias]
			VAR EntradasAtrasadas = 
			    CALCULATE(
			        [Total a Receber],
			        DATEADD( d_Calendario[Data], DiasAtraso, DAY )
			    )
			
			VAR SaidasSemAtraso = [Total a Pagar]
			
			RETURN
			    EntradasAtrasadas - SaidasSemAtraso
			```
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.4 Gestão de Riscos\1.4.1 Atraso de receita
		lineageTag: 22823c70-920a-4570-8a37-d5a92eb71ddb

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Movimentação - Data Quebra' = ```
			
			VAR _SaldoRisco = [Movimentacao Liquida SOB RISCO] // Medida que você já criou.
			
			RETURN
			    // Retorna a menor data (a primeira) que atende ao critério de risco.
			    MINX( 
			        // 1. Itera sobre todas as datas no contexto
			        FILTER( 
			            ALL(d_Calendario[Data]), 
			            // 2. Filtra apenas as datas onde o Saldo Sob Risco é negativo
			            [Movimentacao Liquida SOB RISCO] < 0 
			        ), 
			        // 3. Retorna a data (o contexto da linha atual)
			        d_Calendario[Data] 
			    )
			```
		formatString: General Date
		displayFolder: 1. INDICADORES\1.4 Gestão de Riscos\1.4.1 Atraso de receita
		lineageTag: 54b84a05-b653-4909-93c1-26d22a37610f

	measure 'Movimentação - Status' = ```
			
			VAR DataQuebra = [Movimentação - Data Quebra] // Sua medida que retorna a data de crise
			VAR DataHoje = TODAY()
			VAR DiasParaQuebra = DATEDIFF(DataHoje, DataQuebra, DAY) // Calcula a diferença em dias
			
			RETURN
			    IF(
			        ISBLANK(DataQuebra),
			        "CAIXA SAUDÁVEL (Risco Controlado)", // Se não houver data, está seguro.
			        
			        // Se houver data:
			        "PREJUÍZO em " & 
			        FORMAT(DiasParaQuebra, "#") & 
			        " dias (Risco Alto)"
			    )
			```
		displayFolder: 1. INDICADORES\1.4 Gestão de Riscos\1.4.1 Atraso de receita
		lineageTag: 8c35f692-efe9-4079-b5f7-3d76249d14cb

	measure 'Entradas Previstas (Risco de Inadimplência)' = [Total a Receber] * (1- 'aux_Risco Inadimplência'[Risco Inadimplência %])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.4 Gestão de Riscos\1.4.2 Inadimplência
		lineageTag: eefe7ab2-991f-4000-a6b6-8680d9356d14

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Saídas Previstas (Risco de Inadimplência)' = [Total a Pagar] * (1+ 'aux_Aumento despesas'[Valor aux_Aumento despesas])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.4 Gestão de Riscos\1.4.3 Aumento de despesas
		lineageTag: 4569e737-2033-45e6-9e1f-6501f2530568

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Movimentacao Liquida (RISCO TOTAL)' = ```
			
			VAR DiasAtraso = [Atraso de Receita dias]
			VAR PctInadimplencia = [Risco Inadimplência %]
			VAR PctAumentoCusto = [Valor aux_Aumento despesas]
			
			// 1. Aplica o Fator de Inadimplência e o Atraso (DATEADD)
			VAR EntradasAjustadas = 
			    CALCULATE(
			        [Total a Receber] * (1 - PctInadimplencia), // Aplica Inadimplência
			        DATEADD( d_Calendario[Data], DiasAtraso, DAY )    // Aplica Atraso
			    )
			
			// 2. Aplica o Fator de Aumento de Custo
			VAR SaidasAjustadas = 
			    [Total a Pagar] * (1 + PctAumentoCusto)
			
			RETURN
			    EntradasAjustadas - SaidasAjustadas
			```
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: 1. INDICADORES\1.4 Gestão de Riscos\1.4.4 Movimentação sob Riscos
		lineageTag: bbb39443-9a04-48f9-a923-018966459535

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Inadimplência - Data Quebra' = ```
			
			VAR _SaldoRisco = [Entradas Previstas (Risco de Inadimplência)] // Medida que você já criou.
			
			RETURN
			    // Retorna a menor data (a primeira) que atende ao critério de risco.
			    MINX( 
			        // 1. Itera sobre todas as datas no contexto
			        FILTER( 
			            ALL(d_Calendario[Data]), 
			            // 2. Filtra apenas as datas onde o Saldo Sob Risco é negativo
			            [Entradas Previstas (Risco de Inadimplência)] < 0 
			        ), 
			        // 3. Retorna a data (o contexto da linha atual)
			        d_Calendario[Data] 
			    )
			```
		formatString: General Date
		displayFolder: 1. INDICADORES\1.4 Gestão de Riscos\1.4.2 Inadimplência
		lineageTag: a795126e-5f59-43e5-a8d4-edf6dd59800e

	measure 'Inadimplência - Status' = ```
			
			VAR DataQuebra = [Inadimplência - Data Quebra] // Sua medida que retorna a data de crise
			VAR DataHoje = TODAY()
			VAR DiasParaQuebra = DATEDIFF(DataHoje, DataQuebra, DAY) // Calcula a diferença em dias
			
			RETURN
			    IF(
			        ISBLANK(DataQuebra),
			        "CAIXA SAUDÁVEL (Risco Controlado)", // Se não houver data, está seguro.
			        
			        // Se houver data:
			        "PREJUÍZO em " & 
			        FORMAT(DiasParaQuebra, "#") & 
			        " dias (Risco Alto)"
			    )
			```
		displayFolder: 1. INDICADORES\1.4 Gestão de Riscos\1.4.2 Inadimplência
		lineageTag: 86d917d5-0234-491f-9950-78eb9ea6b679

	measure 'Aumento Despesas - Data Quebra' = ```
			
			VAR _SaldoRisco = [Saídas Previstas (Risco de Inadimplência)] // Medida que você já criou.
			
			RETURN
			    // Retorna a menor data (a primeira) que atende ao critério de risco.
			    MINX( 
			        // 1. Itera sobre todas as datas no contexto
			        FILTER( 
			            ALL(d_Calendario[Data]), 
			            // 2. Filtra apenas as datas onde o Saldo Sob Risco é negativo
			            [Saídas Previstas (Risco de Inadimplência)] < 0 
			        ), 
			        // 3. Retorna a data (o contexto da linha atual)
			        d_Calendario[Data] 
			    )
			```
		formatString: General Date
		displayFolder: 1. INDICADORES\1.4 Gestão de Riscos\1.4.3 Aumento de despesas
		lineageTag: 3859224e-ce14-4de9-a67e-7371600209f6

	measure 'Aumento Despesas - Status' = ```
			
			VAR DataQuebra = [Aumento Despesas - Data Quebra] // Sua medida que retorna a data de crise
			VAR DataHoje = TODAY()
			VAR DiasParaQuebra = DATEDIFF(DataHoje, DataQuebra, DAY) // Calcula a diferença em dias
			
			RETURN
			    IF(
			        ISBLANK(DataQuebra),
			        "CAIXA SAUDÁVEL (Risco Controlado)", // Se não houver data, está seguro.
			        
			        // Se houver data:
			        "PREJUÍZO em " & 
			        FORMAT(DiasParaQuebra, "#") & 
			        " dias (Risco Alto)"
			    )
			```
		displayFolder: 1. INDICADORES\1.4 Gestão de Riscos\1.4.3 Aumento de despesas
		lineageTag: 8e328a8e-9bf4-4213-bd30-a9656c0d6bc7

	measure 'Movimentação Total - Data Quebra' = ```
			
			VAR _SaldoRisco = [Movimentacao Liquida (RISCO TOTAL)] // Medida que você já criou.
			
			RETURN
			    // Retorna a menor data (a primeira) que atende ao critério de risco.
			    MINX( 
			        // 1. Itera sobre todas as datas no contexto
			        FILTER( 
			            ALL(d_Calendario[Data]), 
			            // 2. Filtra apenas as datas onde o Saldo Sob Risco é negativo
			            [Movimentacao Liquida (RISCO TOTAL)] < 0 
			        ), 
			        // 3. Retorna a data (o contexto da linha atual)
			        d_Calendario[Data] 
			    )
			```
		formatString: General Date
		displayFolder: 1. INDICADORES\1.4 Gestão de Riscos\1.4.4 Movimentação sob Riscos
		lineageTag: 2dffcba9-7ead-411b-92e3-8b8968cae2a1

	measure 'Movimentação Total - Status' = ```
			
			VAR DataQuebra = [Movimentação - Data Quebra] // Sua medida que retorna a data de crise
			VAR DataHoje = TODAY()
			VAR DiasParaQuebra = DATEDIFF(DataHoje, DataQuebra, DAY) // Calcula a diferença em dias
			
			RETURN
			    IF(
			        ISBLANK(DataQuebra),
			        "CAIXA SAUDÁVEL (Risco Controlado)", // Se não houver data, está seguro.
			        
			        // Se houver data:
			        "PREJUÍZO em " & 
			        FORMAT(DiasParaQuebra, "#") & 
			        " dias (Risco Alto)"
			    )
			```
		displayFolder: 1. INDICADORES\1.4 Gestão de Riscos\1.4.4 Movimentação sob Riscos
		lineageTag: aeff9f51-f615-47df-9bfc-2d0e6ddad387

	measure crd_DisponibilidadeImediata = ```
			
			VAR titulo = "Disponibilidade Imediata" 
			VAR cor_primaria = "#389EB3"
			VAR cor_secundaria = "black"
			VAR cor_neutra = "#E4E4E4"
			VAR icone = "<svg xmlns='http://www.w3.org/2000/svg' class='icon' viewBox='0 0 16 16'>
			  <path d='M5.5 9.511c.076.954.83 1.697 2.182 1.785V12h.6v-.709c1.4-.098 2.218-.846 2.218-1.932 0-.987-.626-1.496-1.745-1.76l-.473-.112V5.57c.6.068.982.396 1.074.85h1.052c-.076-.919-.864-1.638-2.126-1.716V4h-.6v.719c-1.195.117-2.01.836-2.01 1.853 0 .9.606 1.472 1.613 1.707l.397.098v2.034c-.615-.093-1.022-.43-1.114-.9zm2.177-2.166c-.59-.137-.91-.416-.91-.836 0-.47.345-.822.915-.925v1.76h-.005zm.692 1.193c.717.166 1.048.435 1.048.91 0 .542-.412.914-1.135.982V8.518z'/>
			  <path d='M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16'/>
			  <path d='M8 13.5a5.5 5.5 0 1 1 0-11 5.5 5.5 0 0 1 0 11m0 .5A6 6 0 1 0 8 2a6 6 0 0 0 0 12'/>
			</svg>"
			VAR valor = "R$ " & FORMAT([Saldo Atual], "#,#.00")
			RETURN
			"<html lang='pt-br'>
			<head>
			  <meta charset='UTF-8'>
			  <meta name='viewport' content='width=device-width, initial-scale=1.0'>
			  <style>
			    .card {
			      width: 320px;
			      height: 130px;
			      background-color: " & cor_neutra & ";
			      border-radius: 10px;
			      display: flex;
			      flex-direction: column;
			      align-items: center;
			      justify-content: center;
			      position: relative;
			      transition: all 0.3s ease-in-out;
			      cursor: pointer;
			    }
			    .title {
			      font-size: 15px;
			      font-weight: bold;
			      color: " & cor_secundaria & ";
			      position: absolute;
			      top: 5px;
			      transition: color 0.3s ease;
			    }
			    .icon {
			      margin-top:7%;
			      margin-bottom: 2%;
			      width: 35px;
			      fill: " & cor_secundaria & ";
			      height: 35px;
			      transition: fill 0.3s ease;
			    }
			    .value {
			      font-size: 20px;
			      color: " & cor_secundaria & ";
			      font-weight: bold;
			      transition: color 0.3s ease;
			    }
			    
			    .card:hover {
			      transform: scale(1.05);
			      background-color: " & cor_primaria & ";
			    }
			    .card:hover .value {
			      color: " & cor_neutra & ";
			    }
			    .card:hover .title {
			      color: " & cor_neutra & ";
			    }
			    .card:hover .icon path {
			      fill: " & cor_neutra & ";
			    }
			  </style>
			</head>
			<body>
			  <div class='card'>
			    <div class='title'>
			      " & titulo & "
			    </div>
			    <div class='icon'>
			      " & icone & "
			    </div>
			    <div class='value'>
			      " & valor & "
			    </div>
			  </div>
			</body>
			</html>"
			
			```
		displayFolder: 2. VISUAL\2.1 Tela 1\2.1.1 Cards
		lineageTag: 6f14161e-af5d-4cb1-ba7b-63b0fd4f6b16

	measure 'crd_Total Recebido' = ```
			
			VAR titulo = "Total Recebido" 
			VAR cor_primaria = "#389EB3"
			VAR cor_secundaria = "black"
			VAR cor_neutra = "#E4E4E4"
			VAR icone = "<svg xmlns='http://www.w3.org/2000/svg' class='icon' viewBox='0 0 16 16'>
			  <path d='M1 3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1zm7 8a2 2 0 1 0 0-4 2 2 0 0 0 0 4'/>
			  <path d='M0 5a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1zm3 0a2 2 0 0 1-2 2v4a2 2 0 0 1 2 2h10a2 2 0 0 1 2-2V7a2 2 0 0 1-2-2z'/>
			</svg>"
			VAR valor = "R$ " & FORMAT([Total Recebido], "#,#.00")
			RETURN
			"<html lang='pt-br'>
			<head>
			  <meta charset='UTF-8'>
			  <meta name='viewport' content='width=device-width, initial-scale=1.0'>
			  <style>
			    .card {
			      width: 320px;
			      height: 130px;
			      background-color: " & cor_neutra & ";
			      border-radius: 10px;
			      display: flex;
			      flex-direction: column;
			      align-items: center;
			      justify-content: center;
			      position: relative;
			      transition: all 0.3s ease-in-out;
			      cursor: pointer;
			    }
			    .title {
			      font-size: 15px;
			      font-weight: bold;
			      color: " & cor_secundaria & ";
			      position: absolute;
			      top: 5px;
			      transition: color 0.3s ease;
			    }
			    .icon {
			      margin-top:7%;
			      margin-bottom: 2%;
			      width: 35px;
			      fill: " & cor_secundaria & ";
			      height: 35px;
			      transition: fill 0.3s ease;
			    }
			    .value {
			      font-size: 20px;
			      color: " & cor_secundaria & ";
			      font-weight: bold;
			      transition: color 0.3s ease;
			    }
			    
			    .card:hover {
			      transform: scale(1.05);
			      background-color: " & cor_primaria & ";
			    }
			    .card:hover .value {
			      color: " & cor_neutra & ";
			    }
			    .card:hover .title {
			      color: " & cor_neutra & ";
			    }
			    .card:hover .icon path {
			      fill: " & cor_neutra & ";
			    }
			  </style>
			</head>
			<body>
			  <div class='card'>
			    <div class='title'>
			      " & titulo & "
			    </div>
			    <div class='icon'>
			      " & icone & "
			    </div>
			    <div class='value'>
			      " & valor & "
			    </div>
			  </div>
			</body>
			</html>"
			
			```
		displayFolder: 2. VISUAL\2.1 Tela 1\2.1.1 Cards
		lineageTag: 621642d3-454d-4144-a0b7-a30a8d4959fb

	measure 'crd_Saldo Previsto' = ```
			
			VAR titulo = "Saldo Previsto" 
			VAR cor_primaria = "#389EB3"
			VAR cor_secundaria = "black"
			VAR cor_neutra = "#E4E4E4"
			VAR icone = "<svg xmlns='http://www.w3.org/2000/svg' class='icon' viewBox='0 0 16 16'>
			  <path d='M2.5 15a.5.5 0 1 1 0-1h1v-1a4.5 4.5 0 0 1 2.557-4.06c.29-.139.443-.377.443-.59v-.7c0-.213-.154-.451-.443-.59A4.5 4.5 0 0 1 3.5 3V2h-1a.5.5 0 0 1 0-1h11a.5.5 0 0 1 0 1h-1v1a4.5 4.5 0 0 1-2.557 4.06c-.29.139-.443.377-.443.59v.7c0 .213.154.451.443.59A4.5 4.5 0 0 1 12.5 13v1h1a.5.5 0 0 1 0 1zm2-13v1c0 .537.12 1.045.337 1.5h6.326c.216-.455.337-.963.337-1.5V2zm3 6.35c0 .701-.478 1.236-1.011 1.492A3.5 3.5 0 0 0 4.5 13s.866-1.299 3-1.48zm1 0v3.17c2.134.181 3 1.48 3 1.48a3.5 3.5 0 0 0-1.989-3.158C8.978 9.586 8.5 9.052 8.5 8.351z'/>
			</svg>"
			VAR valor = "R$ " & FORMAT([Saldo Previsto], "#,#.00")
			RETURN
			"<html lang='pt-br'>
			<head>
			  <meta charset='UTF-8'>
			  <meta name='viewport' content='width=device-width, initial-scale=1.0'>
			  <style>
			    .card {
			      width: 320px;
			      height: 130px;
			      background-color: " & cor_neutra & ";
			      border-radius: 10px;
			      display: flex;
			      flex-direction: column;
			      align-items: center;
			      justify-content: center;
			      position: relative;
			      transition: all 0.3s ease-in-out;
			      cursor: pointer;
			    }
			    .title {
			      font-size: 15px;
			      font-weight: bold;
			      color: " & cor_secundaria & ";
			      position: absolute;
			      top: 5px;
			      transition: color 0.3s ease;
			    }
			    .icon {
			      margin-top:7%;
			      margin-bottom: 2%;
			      width: 35px;
			      fill: " & cor_secundaria & ";
			      height: 35px;
			      transition: fill 0.3s ease;
			    }
			    .value {
			      font-size: 20px;
			      color: " & cor_secundaria & ";
			      font-weight: bold;
			      transition: color 0.3s ease;
			    }
			    
			    .card:hover {
			      transform: scale(1.05);
			      background-color: " & cor_primaria & ";
			    }
			    .card:hover .value {
			      color: " & cor_neutra & ";
			    }
			    .card:hover .title {
			      color: " & cor_neutra & ";
			    }
			    .card:hover .icon path {
			      fill: " & cor_neutra & ";
			    }
			  </style>
			</head>
			<body>
			  <div class='card'>
			    <div class='title'>
			      " & titulo & "
			    </div>
			    <div class='icon'>
			      " & icone & "
			    </div>
			    <div class='value'>
			      " & valor & "
			    </div>
			  </div>
			</body>
			</html>"
			
			```
		displayFolder: 2. VISUAL\2.1 Tela 1\2.1.1 Cards
		lineageTag: 374ff859-3831-485b-b948-73536fe5a295

	measure 'crd_Total Pago' = ```
			
			VAR titulo = "Total Pago" 
			VAR cor_primaria = "#389EB3"
			VAR cor_secundaria = "black"
			VAR cor_neutra = "#E4E4E4"
			VAR icone = "<svg xmlns='http://www.w3.org/2000/svg' class='icon' viewBox='0 0 16 16'>
			  <path d='M8 10a2 2 0 1 0 0-4 2 2 0 0 0 0 4'/>
			  <path d='M0 4a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1zm3 0a2 2 0 0 1-2 2v4a2 2 0 0 1 2 2h10a2 2 0 0 1 2-2V6a2 2 0 0 1-2-2z'/>
			</svg>"
			VAR valor = "R$ " & FORMAT([Total Pago], "#,#.00")
			RETURN
			"<html lang='pt-br'>
			<head>
			  <meta charset='UTF-8'>
			  <meta name='viewport' content='width=device-width, initial-scale=1.0'>
			  <style>
			    .card {
			      width: 320px;
			      height: 130px;
			      background-color: " & cor_neutra & ";
			      border-radius: 10px;
			      display: flex;
			      flex-direction: column;
			      align-items: center;
			      justify-content: center;
			      position: relative;
			      transition: all 0.3s ease-in-out;
			      cursor: pointer;
			    }
			    .title {
			      font-size: 15px;
			      font-weight: bold;
			      color: " & cor_secundaria & ";
			      position: absolute;
			      top: 5px;
			      transition: color 0.3s ease;
			    }
			    .icon {
			      margin-top:7%;
			      margin-bottom: 2%;
			      width: 35px;
			      fill: " & cor_secundaria & ";
			      height: 35px;
			      transition: fill 0.3s ease;
			    }
			    .value {
			      font-size: 20px;
			      color: " & cor_secundaria & ";
			      font-weight: bold;
			      transition: color 0.3s ease;
			    }
			    
			    .card:hover {
			      transform: scale(1.05);
			      background-color: " & cor_primaria & ";
			    }
			    .card:hover .value {
			      color: " & cor_neutra & ";
			    }
			    .card:hover .title {
			      color: " & cor_neutra & ";
			    }
			    .card:hover .icon path {
			      fill: " & cor_neutra & ";
			    }
			  </style>
			</head>
			<body>
			  <div class='card'>
			    <div class='title'>
			      " & titulo & "
			    </div>
			    <div class='icon'>
			      " & icone & "
			    </div>
			    <div class='value'>
			      " & valor & "
			    </div>
			  </div>
			</body>
			</html>"
			
			```
		displayFolder: 2. VISUAL\2.1 Tela 1\2.1.1 Cards
		lineageTag: 960fcf72-e5cd-4992-b84c-ea69982ea940

	measure 'crd_Total a Receber' = ```
			
			VAR titulo = "Total a Receber" 
			VAR cor_primaria = "#389EB3"
			VAR cor_secundaria = "black"
			VAR cor_neutra = "#E4E4E4"
			VAR icone = "<svg xmlns='http://www.w3.org/2000/svg' class='icon' viewBox='0 0 16 16'>
			  <path d='M5.5 9.511c.076.954.83 1.697 2.182 1.785V12h.6v-.709c1.4-.098 2.218-.846 2.218-1.932 0-.987-.626-1.496-1.745-1.76l-.473-.112V5.57c.6.068.982.396 1.074.85h1.052c-.076-.919-.864-1.638-2.126-1.716V4h-.6v.719c-1.195.117-2.01.836-2.01 1.853 0 .9.606 1.472 1.613 1.707l.397.098v2.034c-.615-.093-1.022-.43-1.114-.9zm2.177-2.166c-.59-.137-.91-.416-.91-.836 0-.47.345-.822.915-.925v1.76h-.005zm.692 1.193c.717.166 1.048.435 1.048.91 0 .542-.412.914-1.135.982V8.518z'/>
			  <path d='M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16'/>
			  <path d='M8 13.5a5.5 5.5 0 1 1 0-11 5.5 5.5 0 0 1 0 11m0 .5A6 6 0 1 0 8 2a6 6 0 0 0 0 12'/>
			</svg>"
			VAR valor = "R$ " & FORMAT([Total a Receber], "#,#.00")
			RETURN
			"<html lang='pt-br'>
			<head>
			  <meta charset='UTF-8'>
			  <meta name='viewport' content='width=device-width, initial-scale=1.0'>
			  <style>
			    .card {
			      width: 320px;
			      height: 130px;
			      background-color: " & cor_neutra & ";
			      border-radius: 10px;
			      display: flex;
			      flex-direction: column;
			      align-items: center;
			      justify-content: center;
			      position: relative;
			      transition: all 0.3s ease-in-out;
			      cursor: pointer;
			    }
			    .title {
			      font-size: 15px;
			      font-weight: bold;
			      color: " & cor_secundaria & ";
			      position: absolute;
			      top: 5px;
			      transition: color 0.3s ease;
			    }
			    .icon {
			      margin-top:7%;
			      margin-bottom: 2%;
			      width: 35px;
			      fill: " & cor_secundaria & ";
			      height: 35px;
			      transition: fill 0.3s ease;
			    }
			    .value {
			      font-size: 20px;
			      color: " & cor_secundaria & ";
			      font-weight: bold;
			      transition: color 0.3s ease;
			    }
			    
			    .card:hover {
			      transform: scale(1.05);
			      background-color: " & cor_primaria & ";
			    }
			    .card:hover .value {
			      color: " & cor_neutra & ";
			    }
			    .card:hover .title {
			      color: " & cor_neutra & ";
			    }
			    .card:hover .icon path {
			      fill: " & cor_neutra & ";
			    }
			  </style>
			</head>
			<body>
			  <div class='card'>
			    <div class='title'>
			      " & titulo & "
			    </div>
			    <div class='icon'>
			      " & icone & "
			    </div>
			    <div class='value'>
			      " & valor & "
			    </div>
			  </div>
			</body>
			</html>"
			
			```
		displayFolder: 2. VISUAL\2.2 Tela 2\2.2.1 Cards
		lineageTag: 4d86e968-bb2b-49c7-a249-62f02aa92cb3

		changedProperty = IsHidden

	measure 'crd_Total a receber em Aberto' = ```
			
			VAR titulo = "Total a receber em Aberto" 
			VAR cor_primaria = "#389EB3"
			VAR cor_secundaria = "black"
			VAR cor_neutra = "#E4E4E4"
			VAR icone = "<svg xmlns='http://www.w3.org/2000/svg' class='icon' viewBox='0 0 16 16'>
			  <path d='M2.5 15a.5.5 0 1 1 0-1h1v-1a4.5 4.5 0 0 1 2.557-4.06c.29-.139.443-.377.443-.59v-.7c0-.213-.154-.451-.443-.59A4.5 4.5 0 0 1 3.5 3V2h-1a.5.5 0 0 1 0-1h11a.5.5 0 0 1 0 1h-1v1a4.5 4.5 0 0 1-2.557 4.06c-.29.139-.443.377-.443.59v.7c0 .213.154.451.443.59A4.5 4.5 0 0 1 12.5 13v1h1a.5.5 0 0 1 0 1zm2-13v1c0 .537.12 1.045.337 1.5h6.326c.216-.455.337-.963.337-1.5V2zm3 6.35c0 .701-.478 1.236-1.011 1.492A3.5 3.5 0 0 0 4.5 13s.866-1.299 3-1.48zm1 0v3.17c2.134.181 3 1.48 3 1.48a3.5 3.5 0 0 0-1.989-3.158C8.978 9.586 8.5 9.052 8.5 8.351z'/>
			</svg>"
			VAR valor = "R$ " & FORMAT([Total a receber em Aberto], "#,#.00")
			RETURN
			"<html lang='pt-br'>
			<head>
			  <meta charset='UTF-8'>
			  <meta name='viewport' content='width=device-width, initial-scale=1.0'>
			  <style>
			    .card {
			      width: 320px;
			      height: 130px;
			      background-color: " & cor_neutra & ";
			      border-radius: 10px;
			      display: flex;
			      flex-direction: column;
			      align-items: center;
			      justify-content: center;
			      position: relative;
			      transition: all 0.3s ease-in-out;
			      cursor: pointer;
			    }
			    .title {
			      font-size: 15px;
			      font-weight: bold;
			      color: " & cor_secundaria & ";
			      position: absolute;
			      top: 5px;
			      transition: color 0.3s ease;
			    }
			    .icon {
			      margin-top:7%;
			      margin-bottom: 2%;
			      width: 35px;
			      fill: " & cor_secundaria & ";
			      height: 35px;
			      transition: fill 0.3s ease;
			    }
			    .value {
			      font-size: 20px;
			      color: " & cor_secundaria & ";
			      font-weight: bold;
			      transition: color 0.3s ease;
			    }
			    
			    .card:hover {
			      transform: scale(1.05);
			      background-color: " & cor_primaria & ";
			    }
			    .card:hover .value {
			      color: " & cor_neutra & ";
			    }
			    .card:hover .title {
			      color: " & cor_neutra & ";
			    }
			    .card:hover .icon path {
			      fill: " & cor_neutra & ";
			    }
			  </style>
			</head>
			<body>
			  <div class='card'>
			    <div class='title'>
			      " & titulo & "
			    </div>
			    <div class='icon'>
			      " & icone & "
			    </div>
			    <div class='value'>
			      " & valor & "
			    </div>
			  </div>
			</body>
			</html>"
			
			```
		displayFolder: 2. VISUAL\2.2 Tela 2\2.2.1 Cards
		lineageTag: 1e844f4b-1335-4494-ad8e-45211e41c29d

		changedProperty = IsHidden

	measure 'crd_Total a receber atrasados' = ```
			
			VAR titulo = "Total a receber atrasados" 
			VAR cor_primaria = "#389EB3"
			VAR cor_secundaria = "black"
			VAR cor_neutra = "#E4E4E4"
			VAR icone = "<svg xmlns='http://www.w3.org/2000/svg' class='icon' viewBox='0 0 16 16'>
			  <path d='M2.5 15a.5.5 0 1 1 0-1h1v-1a4.5 4.5 0 0 1 2.557-4.06c.29-.139.443-.377.443-.59v-.7c0-.213-.154-.451-.443-.59A4.5 4.5 0 0 1 3.5 3V2h-1a.5.5 0 0 1 0-1h11a.5.5 0 0 1 0 1h-1v1a4.5 4.5 0 0 1-2.557 4.06c-.29.139-.443.377-.443.59v.7c0 .213.154.451.443.59A4.5 4.5 0 0 1 12.5 13v1h1a.5.5 0 0 1 0 1zm2-13v1c0 .537.12 1.045.337 1.5h6.326c.216-.455.337-.963.337-1.5V2zm3 6.35c0 .701-.478 1.236-1.011 1.492A3.5 3.5 0 0 0 4.5 13s.866-1.299 3-1.48zm1 0v3.17c2.134.181 3 1.48 3 1.48a3.5 3.5 0 0 0-1.989-3.158C8.978 9.586 8.5 9.052 8.5 8.351z'/>
			</svg>"
			VAR valor = "R$ " & FORMAT([Total a receber atrasados], "#,#.00")
			RETURN
			"<html lang='pt-br'>
			<head>
			  <meta charset='UTF-8'>
			  <meta name='viewport' content='width=device-width, initial-scale=1.0'>
			  <style>
			    .card {
			      width: 320px;
			      height: 130px;
			      background-color: " & cor_neutra & ";
			      border-radius: 10px;
			      display: flex;
			      flex-direction: column;
			      align-items: center;
			      justify-content: center;
			      position: relative;
			      transition: all 0.3s ease-in-out;
			      cursor: pointer;
			    }
			    .title {
			      font-size: 15px;
			      font-weight: bold;
			      color: " & cor_secundaria & ";
			      position: absolute;
			      top: 5px;
			      transition: color 0.3s ease;
			    }
			    .icon {
			      margin-top:7%;
			      margin-bottom: 2%;
			      width: 35px;
			      fill: " & cor_secundaria & ";
			      height: 35px;
			      transition: fill 0.3s ease;
			    }
			    .value {
			      font-size: 20px;
			      color: " & cor_secundaria & ";
			      font-weight: bold;
			      transition: color 0.3s ease;
			    }
			    
			    .card:hover {
			      transform: scale(1.05);
			      background-color: " & cor_primaria & ";
			    }
			    .card:hover .value {
			      color: " & cor_neutra & ";
			    }
			    .card:hover .title {
			      color: " & cor_neutra & ";
			    }
			    .card:hover .icon path {
			      fill: " & cor_neutra & ";
			    }
			  </style>
			</head>
			<body>
			  <div class='card'>
			    <div class='title'>
			      " & titulo & "
			    </div>
			    <div class='icon'>
			      " & icone & "
			    </div>
			    <div class='value'>
			      " & valor & "
			    </div>
			  </div>
			</body>
			</html>"
			
			```
		displayFolder: 2. VISUAL\2.2 Tela 2\2.2.1 Cards
		lineageTag: 6b6026c5-cd99-485c-9746-aeb966e34ea0

		changedProperty = IsHidden

	measure 'crd_Total a Pagar' = ```
			
			VAR titulo = "Total a Pagar" 
			VAR cor_primaria = "#389EB3"
			VAR cor_secundaria = "black"
			VAR cor_neutra = "#E4E4E4"
			VAR icone = "<svg xmlns='http://www.w3.org/2000/svg' class='icon' viewBox='0 0 16 16'>
			  <path d='M5.5 9.511c.076.954.83 1.697 2.182 1.785V12h.6v-.709c1.4-.098 2.218-.846 2.218-1.932 0-.987-.626-1.496-1.745-1.76l-.473-.112V5.57c.6.068.982.396 1.074.85h1.052c-.076-.919-.864-1.638-2.126-1.716V4h-.6v.719c-1.195.117-2.01.836-2.01 1.853 0 .9.606 1.472 1.613 1.707l.397.098v2.034c-.615-.093-1.022-.43-1.114-.9zm2.177-2.166c-.59-.137-.91-.416-.91-.836 0-.47.345-.822.915-.925v1.76h-.005zm.692 1.193c.717.166 1.048.435 1.048.91 0 .542-.412.914-1.135.982V8.518z'/>
			  <path d='M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16'/>
			  <path d='M8 13.5a5.5 5.5 0 1 1 0-11 5.5 5.5 0 0 1 0 11m0 .5A6 6 0 1 0 8 2a6 6 0 0 0 0 12'/>
			</svg>"
			VAR valor = "R$ " & FORMAT([Total a Pagar], "#,#.00")
			RETURN
			"<html lang='pt-br'>
			<head>
			  <meta charset='UTF-8'>
			  <meta name='viewport' content='width=device-width, initial-scale=1.0'>
			  <style>
			    .card {
			      width: 320px;
			      height: 130px;
			      background-color: " & cor_neutra & ";
			      border-radius: 10px;
			      display: flex;
			      flex-direction: column;
			      align-items: center;
			      justify-content: center;
			      position: relative;
			      transition: all 0.3s ease-in-out;
			      cursor: pointer;
			    }
			    .title {
			      font-size: 15px;
			      font-weight: bold;
			      color: " & cor_secundaria & ";
			      position: absolute;
			      top: 5px;
			      transition: color 0.3s ease;
			    }
			    .icon {
			      margin-top:7%;
			      margin-bottom: 2%;
			      width: 35px;
			      fill: " & cor_secundaria & ";
			      height: 35px;
			      transition: fill 0.3s ease;
			    }
			    .value {
			      font-size: 20px;
			      color: " & cor_secundaria & ";
			      font-weight: bold;
			      transition: color 0.3s ease;
			    }
			    
			    .card:hover {
			      transform: scale(1.05);
			      background-color: " & cor_primaria & ";
			    }
			    .card:hover .value {
			      color: " & cor_neutra & ";
			    }
			    .card:hover .title {
			      color: " & cor_neutra & ";
			    }
			    .card:hover .icon path {
			      fill: " & cor_neutra & ";
			    }
			  </style>
			</head>
			<body>
			  <div class='card'>
			    <div class='title'>
			      " & titulo & "
			    </div>
			    <div class='icon'>
			      " & icone & "
			    </div>
			    <div class='value'>
			      " & valor & "
			    </div>
			  </div>
			</body>
			</html>"
			
			```
		displayFolder: 2. VISUAL\2.3 Tela 3\2.3.1 Cards
		lineageTag: a1be541a-239f-46c5-b5d6-9ce1fc507863

	measure 'crd_Total a pagar em Aberto' = ```
			
			VAR titulo = "Total a pagar em Aberto" 
			VAR cor_primaria = "#389EB3"
			VAR cor_secundaria = "black"
			VAR cor_neutra = "#E4E4E4"
			VAR icone = "<svg xmlns='http://www.w3.org/2000/svg' class='icon' viewBox='0 0 16 16'>
			  <path d='M2.5 15a.5.5 0 1 1 0-1h1v-1a4.5 4.5 0 0 1 2.557-4.06c.29-.139.443-.377.443-.59v-.7c0-.213-.154-.451-.443-.59A4.5 4.5 0 0 1 3.5 3V2h-1a.5.5 0 0 1 0-1h11a.5.5 0 0 1 0 1h-1v1a4.5 4.5 0 0 1-2.557 4.06c-.29.139-.443.377-.443.59v.7c0 .213.154.451.443.59A4.5 4.5 0 0 1 12.5 13v1h1a.5.5 0 0 1 0 1zm2-13v1c0 .537.12 1.045.337 1.5h6.326c.216-.455.337-.963.337-1.5V2zm3 6.35c0 .701-.478 1.236-1.011 1.492A3.5 3.5 0 0 0 4.5 13s.866-1.299 3-1.48zm1 0v3.17c2.134.181 3 1.48 3 1.48a3.5 3.5 0 0 0-1.989-3.158C8.978 9.586 8.5 9.052 8.5 8.351z'/>
			</svg>"
			VAR valor = "R$ " & FORMAT([Total a pagar em Aberto], "#,#.00")
			RETURN
			"<html lang='pt-br'>
			<head>
			  <meta charset='UTF-8'>
			  <meta name='viewport' content='width=device-width, initial-scale=1.0'>
			  <style>
			    .card {
			      width: 320px;
			      height: 130px;
			      background-color: " & cor_neutra & ";
			      border-radius: 10px;
			      display: flex;
			      flex-direction: column;
			      align-items: center;
			      justify-content: center;
			      position: relative;
			      transition: all 0.3s ease-in-out;
			      cursor: pointer;
			    }
			    .title {
			      font-size: 15px;
			      font-weight: bold;
			      color: " & cor_secundaria & ";
			      position: absolute;
			      top: 5px;
			      transition: color 0.3s ease;
			    }
			    .icon {
			      margin-top:7%;
			      margin-bottom: 2%;
			      width: 35px;
			      fill: " & cor_secundaria & ";
			      height: 35px;
			      transition: fill 0.3s ease;
			    }
			    .value {
			      font-size: 20px;
			      color: " & cor_secundaria & ";
			      font-weight: bold;
			      transition: color 0.3s ease;
			    }
			    
			    .card:hover {
			      transform: scale(1.05);
			      background-color: " & cor_primaria & ";
			    }
			    .card:hover .value {
			      color: " & cor_neutra & ";
			    }
			    .card:hover .title {
			      color: " & cor_neutra & ";
			    }
			    .card:hover .icon path {
			      fill: " & cor_neutra & ";
			    }
			  </style>
			</head>
			<body>
			  <div class='card'>
			    <div class='title'>
			      " & titulo & "
			    </div>
			    <div class='icon'>
			      " & icone & "
			    </div>
			    <div class='value'>
			      " & valor & "
			    </div>
			  </div>
			</body>
			</html>"
			
			```
		displayFolder: 2. VISUAL\2.3 Tela 3\2.3.1 Cards
		lineageTag: fe143e5f-99c3-4efe-8c32-780488638be4

	measure 'crd_Total a pagar atrasados' = ```
			
			VAR titulo = "Total a pagar atrasados" 
			VAR cor_primaria = "#389EB3"
			VAR cor_secundaria = "black"
			VAR cor_neutra = "#E4E4E4"
			VAR icone = "<svg xmlns='http://www.w3.org/2000/svg' class='icon' viewBox='0 0 16 16'>
			  <path d='M2.5 15a.5.5 0 1 1 0-1h1v-1a4.5 4.5 0 0 1 2.557-4.06c.29-.139.443-.377.443-.59v-.7c0-.213-.154-.451-.443-.59A4.5 4.5 0 0 1 3.5 3V2h-1a.5.5 0 0 1 0-1h11a.5.5 0 0 1 0 1h-1v1a4.5 4.5 0 0 1-2.557 4.06c-.29.139-.443.377-.443.59v.7c0 .213.154.451.443.59A4.5 4.5 0 0 1 12.5 13v1h1a.5.5 0 0 1 0 1zm2-13v1c0 .537.12 1.045.337 1.5h6.326c.216-.455.337-.963.337-1.5V2zm3 6.35c0 .701-.478 1.236-1.011 1.492A3.5 3.5 0 0 0 4.5 13s.866-1.299 3-1.48zm1 0v3.17c2.134.181 3 1.48 3 1.48a3.5 3.5 0 0 0-1.989-3.158C8.978 9.586 8.5 9.052 8.5 8.351z'/>
			</svg>"
			VAR valor = "R$ " & FORMAT([Total a pagar atrasados], "#,#.00")
			RETURN
			"<html lang='pt-br'>
			<head>
			  <meta charset='UTF-8'>
			  <meta name='viewport' content='width=device-width, initial-scale=1.0'>
			  <style>
			    .card {
			      width: 320px;
			      height: 130px;
			      background-color: " & cor_neutra & ";
			      border-radius: 10px;
			      display: flex;
			      flex-direction: column;
			      align-items: center;
			      justify-content: center;
			      position: relative;
			      transition: all 0.3s ease-in-out;
			      cursor: pointer;
			    }
			    .title {
			      font-size: 15px;
			      font-weight: bold;
			      color: " & cor_secundaria & ";
			      position: absolute;
			      top: 5px;
			      transition: color 0.3s ease;
			    }
			    .icon {
			      margin-top:7%;
			      margin-bottom: 2%;
			      width: 35px;
			      fill: " & cor_secundaria & ";
			      height: 35px;
			      transition: fill 0.3s ease;
			    }
			    .value {
			      font-size: 20px;
			      color: " & cor_secundaria & ";
			      font-weight: bold;
			      transition: color 0.3s ease;
			    }
			    
			    .card:hover {
			      transform: scale(1.05);
			      background-color: " & cor_primaria & ";
			    }
			    .card:hover .value {
			      color: " & cor_neutra & ";
			    }
			    .card:hover .title {
			      color: " & cor_neutra & ";
			    }
			    .card:hover .icon path {
			      fill: " & cor_neutra & ";
			    }
			  </style>
			</head>
			<body>
			  <div class='card'>
			    <div class='title'>
			      " & titulo & "
			    </div>
			    <div class='icon'>
			      " & icone & "
			    </div>
			    <div class='value'>
			      " & valor & "
			    </div>
			  </div>
			</body>
			</html>"
			
			```
		displayFolder: 2. VISUAL\2.3 Tela 3\2.3.1 Cards
		lineageTag: dabadab7-8f10-4731-a378-89065e39fc2e

	measure icn_Timeline = ```
			
			VAR cor_primaria = "#389EB3"
			VAR cor_secundaria = "#387CB3"
			VAR icone = "<svg xmlns='http://www.w3.org/2000/svg' class='icon' viewBox='0 0 16 16'>
			  <path fill-rule='evenodd' d='M0 0h1v15h15v1H0zm10 3.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-1 0V4.9l-3.613 4.417a.5.5 0 0 1-.74.037L7.06 6.767l-3.656 5.027a.5.5 0 0 1-.808-.588l4-5.5a.5.5 0 0 1 .758-.06l2.609 2.61L13.445 4H10.5a.5.5 0 0 1-.5-.5'/>
			</svg>"
			RETURN
			"<html lang='pt-br'>
			<head>
			  <meta charset='UTF-8'>
			  <meta name='viewport' content='width=device-width, initial-scale=1.0'>
			  <style>
			    .icon {
			      width: 25px;
			      height: 25px;
			      fill: " & cor_primaria & ";
			      transition: fill 0.3s ease;
			    }
			    .card:hover .icon path {
			      transform: scale(0.90);
			      fill: " & cor_secundaria & ";
			    }
			  </style>
			</head>
			<body>
			  <div class='card'>
			    <div class='icon'>
			      " & icone & "
			    </div>
			
			  </div>
			</body>
			</html>"
			
			```
		displayFolder: 2. VISUAL\2.1 Tela 1
		lineageTag: b02c6b89-b68b-42dd-a9de-df56fd07549c

	measure icn_Money = ```
			
			VAR cor_primaria = "#389EB3"
			VAR cor_secundaria = "#387CB3"
			VAR icone = "<svg xmlns='http://www.w3.org/2000/svg' class='icon' viewBox='0 0 16 16'>
			  <path d='M1 3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1zm7 8a2 2 0 1 0 0-4 2 2 0 0 0 0 4'/>
			  <path d='M0 5a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1zm3 0a2 2 0 0 1-2 2v4a2 2 0 0 1 2 2h10a2 2 0 0 1 2-2V7a2 2 0 0 1-2-2z'/>
			</svg>"
			RETURN
			"<html lang='pt-br'>
			<head>
			  <meta charset='UTF-8'>
			  <meta name='viewport' content='width=device-width, initial-scale=1.0'>
			  <style>
			    .icon {
			      width: 35px;
			      height: 35px;
			      fill: " & cor_primaria & ";
			      transition: fill 0.3s ease;
			    }
			    .card:hover .icon path {
			      transform: scale(0.90);
			      fill: " & cor_secundaria & ";
			    }
			  </style>
			</head>
			<body>
			  <div class='card'>
			    <div class='icon'>
			      " & icone & "
			    </div>
			
			  </div>
			</body>
			</html>"
			
			```
		displayFolder: 2. VISUAL\2.1 Tela 1
		lineageTag: c7518cad-9ffc-4383-b1f9-e528267424ce

	measure icn_Cliente = ```
			
			VAR cor_primaria = "#389EB3"
			VAR cor_secundaria = "#387CB3"
			VAR icone = "<svg xmlns='http://www.w3.org/2000/svg' class='icon' viewBox='0 0 16 16'>
			  <path d='M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6m-5.784 6A2.24 2.24 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.3 6.3 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1zM4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5'/>
			</svg>"
			RETURN
			"<html lang='pt-br'>
			<head>
			  <meta charset='UTF-8'>
			  <meta name='viewport' content='width=device-width, initial-scale=1.0'>
			  <style>
			    .icon {
			      width: 35px;
			      height: 35px;
			      fill: " & cor_primaria & ";
			      transition: fill 0.3s ease;
			    }
			    .card:hover .icon path {
			      transform: scale(0.90);
			      fill: " & cor_secundaria & ";
			    }
			  </style>
			</head>
			<body>
			  <div class='card'>
			    <div class='icon'>
			      " & icone & "
			    </div>
			
			  </div>
			</body>
			</html>"
			
			```
		displayFolder: 2. VISUAL\2.2 Tela 2
		lineageTag: f5d172ca-cafb-4803-9f7c-2c488ca728e1

	measure icn_EntradasxSaidas = ```
			
			VAR cor_primaria = "#389EB3"
			VAR cor_secundaria = "#387CB3"
			VAR icone = "<svg xmlns='http://www.w3.org/2000/svg' class='icon' viewBox='0 0 16 16'>
			  <path d='M0 5a5 5 0 0 0 4.027 4.905 6.5 6.5 0 0 1 .544-2.073C3.695 7.536 3.132 6.864 3 5.91h-.5v-.426h.466V5.05q-.001-.07.004-.135H2.5v-.427h.511C3.236 3.24 4.213 2.5 5.681 2.5c.316 0 .59.031.819.085v.733a3.5 3.5 0 0 0-.815-.082c-.919 0-1.538.466-1.734 1.252h1.917v.427h-1.98q-.004.07-.003.147v.422h1.983v.427H3.93c.118.602.468 1.03 1.005 1.229a6.5 6.5 0 0 1 4.97-3.113A5.002 5.002 0 0 0 0 5m16 5.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0m-7.75 1.322c.069.835.746 1.485 1.964 1.562V14h.54v-.62c1.259-.086 1.996-.74 1.996-1.69 0-.865-.563-1.31-1.57-1.54l-.426-.1V8.374c.54.06.884.347.966.745h.948c-.07-.804-.779-1.433-1.914-1.502V7h-.54v.629c-1.076.103-1.808.732-1.808 1.622 0 .787.544 1.288 1.45 1.493l.358.085v1.78c-.554-.08-.92-.376-1.003-.787zm1.96-1.895c-.532-.12-.82-.364-.82-.732 0-.41.311-.719.824-.809v1.54h-.005zm.622 1.044c.645.145.943.38.943.796 0 .474-.37.8-1.02.86v-1.674z'/>
			</svg>"
			RETURN
			"<html lang='pt-br'>
			<head>
			  <meta charset='UTF-8'>
			  <meta name='viewport' content='width=device-width, initial-scale=1.0'>
			  <style>
			    .icon {
			      width: 35px;
			      height: 35px;
			      fill: " & cor_primaria & ";
			      transition: fill 0.3s ease;
			    }
			    .card:hover .icon path {
			      transform: scale(0.90);
			      fill: " & cor_secundaria & ";
			    }
			  </style>
			</head>
			<body>
			  <div class='card'>
			    <div class='icon'>
			      " & icone & "
			    </div>
			
			  </div>
			</body>
			</html>"
			
			```
		displayFolder: 2. VISUAL\2.1 Tela 1
		lineageTag: 2080c29f-93ce-4451-8c07-b88f8244f014

	measure icn_Atraso = ```
			
			VAR cor_primaria = "#389EB3"
			VAR cor_secundaria = "#387CB3"
			VAR icone = "<svg xmlns='http://www.w3.org/2000/svg' class='icon' viewBox='0 0 16 16'>
			  <path d='M6 .5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 0 1H9v1.07a7.001 7.001 0 0 1 3.274 12.474l.601.602a.5.5 0 0 1-.707.708l-.746-.746A6.97 6.97 0 0 1 8 16a6.97 6.97 0 0 1-3.422-.892l-.746.746a.5.5 0 0 1-.707-.708l.602-.602A7.001 7.001 0 0 1 7 2.07V1h-.5A.5.5 0 0 1 6 .5m2.5 5a.5.5 0 0 0-1 0v3.362l-1.429 2.38a.5.5 0 1 0 .858.515l1.5-2.5A.5.5 0 0 0 8.5 9zM.86 5.387A2.5 2.5 0 1 1 4.387 1.86 8.04 8.04 0 0 0 .86 5.387M11.613 1.86a2.5 2.5 0 1 1 3.527 3.527 8.04 8.04 0 0 0-3.527-3.527'/>
			</svg>"
			RETURN
			"<html lang='pt-br'>
			<head>
			  <meta charset='UTF-8'>
			  <meta name='viewport' content='width=device-width, initial-scale=1.0'>
			  <style>
			    .icon {
			      width: 25px;
			      height: 25px;
			      fill: " & cor_primaria & ";
			      transition: fill 0.3s ease;
			    }
			    .card:hover .icon path {
			      transform: scale(0.90);
			      fill: " & cor_secundaria & ";
			    }
			  </style>
			</head>
			<body>
			  <div class='card'>
			    <div class='icon'>
			      " & icone & "
			    </div>
			
			  </div>
			</body>
			</html>"
			
			```
		displayFolder: 2. VISUAL
		lineageTag: 1b55e074-1647-4948-b060-ffedad43c6f4

	measure icn_Inadimplencia = ```
			
			VAR cor_primaria = "#389EB3"
			VAR cor_secundaria = "#387CB3"
			VAR icone = "<svg xmlns='http://www.w3.org/2000/svg' class='icon' viewBox='0 0 16 16'>
			  <path d='M11 5a3 3 0 1 1-6 0 3 3 0 0 1 6 0m-9 8c0 1 1 1 1 1h5.256A4.5 4.5 0 0 1 8 12.5a4.5 4.5 0 0 1 1.544-3.393Q8.844 9.002 8 9c-5 0-6 3-6 4'/>
			  <path d='M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7m-.646-4.854.646.647.646-.647a.5.5 0 0 1 .708.708l-.647.646.647.646a.5.5 0 0 1-.708.708l-.646-.647-.646.647a.5.5 0 0 1-.708-.708l.647-.646-.647-.646a.5.5 0 0 1 .708-.708'/>
			</svg>"
			RETURN
			"<html lang='pt-br'>
			<head>
			  <meta charset='UTF-8'>
			  <meta name='viewport' content='width=device-width, initial-scale=1.0'>
			  <style>
			    .icon {
			      width: 25px;
			      height: 25px;
			      fill: " & cor_primaria & ";
			      transition: fill 0.3s ease;
			    }
			    .card:hover .icon path {
			      transform: scale(0.90);
			      fill: " & cor_secundaria & ";
			    }
			  </style>
			</head>
			<body>
			  <div class='card'>
			    <div class='icon'>
			      " & icone & "
			    </div>
			
			  </div>
			</body>
			</html>"
			
			```
		displayFolder: 2. VISUAL
		lineageTag: 85c481ea-ee73-4d46-9dea-b43a54219404

	column Medidas
		dataType: string
		isHidden
		lineageTag: 501e2c0d-bede-4853-99d0-c31ea8076abc
		summarizeBy: none
		sourceColumn: Medidas

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Medidas = m
		mode: import
		source =
				let
				    Fonte = ""
				in
				    Fonte

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Text

